/**
 * Auto-generated by `supabase gen types typescript`.
 * The hand-written types below are a placeholder mirroring the schema in
 * `supabase/migrations/`. Regenerate after schema changes:
 *
 *     npm run supabase:types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      recipes: {
        Row: {
          id: string;
          slug: string;
          title: string;
          description: string | null;
          cuisine: string | null;
          course: string | null;
          difficulty: string | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number | null;
          hero_image_path: string | null;
          published: boolean;
          like_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          description?: string | null;
          cuisine?: string | null;
          course?: string | null;
          difficulty?: string | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          hero_image_path?: string | null;
          published?: boolean;
          like_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["recipes"]["Insert"]>;
        Relationships: [];
      };
      ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          quantity: number | null;
          unit: string | null;
          name: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          quantity?: number | null;
          unit?: string | null;
          name: string;
          notes?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ingredients"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "ingredients_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      instructions: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          step: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          step: string;
        };
        Update: Partial<Database["public"]["Tables"]["instructions"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "instructions_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      tags: {
        Row: {
          id: string;
          slug: string;
          name: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["tags"]["Insert"]>;
        Relationships: [];
      };
      recipe_tags: {
        Row: {
          recipe_id: string;
          tag_id: string;
        };
        Insert: {
          recipe_id: string;
          tag_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["recipe_tags"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "recipe_tags_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_tags_tag_id_fkey";
            columns: ["tag_id"];
            isOneToOne: false;
            referencedRelation: "tags";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      like_recipe: {
        Args: { p_recipe_id: string };
        Returns: number;
      };
    };
    Enums: { [_ in never]: never };
  };
};
